In [4]:
from gensim.models import Word2Vec
sentences = [["cat", "say", "meow"], ["dog", "say", "woof"]]
model = Word2Vec(sentences, min_count=1)
X= list(model.wv.vocab)
X

['cat', 'say', 'meow', 'dog', 'woof']

In [9]:
model.wv['cat']

array([-0.00447231, -0.00254312,  0.00413848,  0.00235889, -0.00222908,
        0.00027125,  0.00424522, -0.00354292,  0.00195102,  0.00408347,
       -0.00076131,  0.00210524,  0.00180856,  0.00139089, -0.00206442,
        0.00091901,  0.00426566,  0.00115295, -0.00157668, -0.00109072,
        0.00487258,  0.00198404,  0.00121468,  0.00472072, -0.0043147 ,
       -0.00171701, -0.00391312, -0.00080462,  0.00273564, -0.00226597,
       -0.00317003, -0.00445596,  0.00315151, -0.00384618,  0.00301179,
       -0.0011859 , -0.0003467 ,  0.00356145, -0.00133171,  0.00397723,
        0.00409645, -0.00484291,  0.00155808,  0.00064069, -0.00321955,
       -0.00456539,  0.00306861, -0.00278314, -0.0038279 ,  0.0003752 ,
       -0.00236709,  0.00359829,  0.00046793,  0.00015546, -0.00458462,
       -0.00329109,  0.00488929,  0.00190706,  0.00061536,  0.00278601,
       -0.00284752, -0.00331904,  0.00064075, -0.0046827 ,  0.0030879 ,
        0.00471045,  0.00128293, -0.00343656, -0.00038585, -0.00

In [10]:
import keras

ModuleNotFoundError: No module named 'keras'

In [1]:
pip install tensorflow

  Using cached https://files.pythonhosted.org/packages/54/5f/e1b2d83b808f978f51b7ce109315154da3a3d4151aa59686002681f2e109/tensorflow-2.0.0-cp37-cp37m-win_amd64.whl
Note: you may need to restart the kernel to use updated packages.


In [15]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [16]:
import keras

Using TensorFlow backend.


In [17]:
from keras.preprocessing.text import text_to_word_sequence
# define the document
text = 'The quick brown fox jumped over the lazy dog.'
# tokenize the document
result = text_to_word_sequence(text)
print(result)

['the', 'quick', 'brown', 'fox', 'jumped', 'over', 'the', 'lazy', 'dog']


In [22]:
from keras.preprocessing.text import one_hot
from keras.preprocessing.text import text_to_word_sequence
# define the document
text = 'The quick brown fox jumped over the lazy dog.'
# estimate the size of the vocabulary
words = set(text_to_word_sequence(text))
vocab_size = len(words)
print(vocab_size)
# integer encode the document
result = one_hot(text, round(vocab_size*1.3))
print(result)

8
[9, 3, 8, 9, 5, 7, 9, 3, 6]


In [3]:
from keras.preprocessing.text import Tokenizer
# define 5 documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!']
# create the tokenizer
t = Tokenizer()
# fit the tokenizer on the documents
t.fit_on_texts(docs)
print(t.word_counts)
print(t.document_count)
print(t.word_index)
print(t.word_docs)

Using TensorFlow backend.


ModuleNotFoundError: No module named 'tensorflow'

In [25]:
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']

In [26]:
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[49, 40], [44, 16], [3, 29], [43, 16], [13], [45], [19, 29], [7, 44], [19, 16], [43, 2, 40, 27]]


In [28]:
max_length = 4
padded_docs = keras.preprocessing.sequence.pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[49 40  0  0]
 [44 16  0  0]
 [ 3 29  0  0]
 [43 16  0  0]
 [13  0  0  0]
 [45  0  0  0]
 [19 29  0  0]
 [ 7 44  0  0]
 [19 16  0  0]
 [43  2 40 27]]


In [31]:
from keras.models import Sequential
from keras.layers import *

# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_1 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [42]:
# define class labels
labels = [1,1,1,1,1,0,0,0,0,0]
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

C:\Users\hemanshu.waghulde\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Accuracy: 89.999998


In [2]:
import numpy as np
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = ([1,1,1,1,1,0,0,0,0,0])
# prepare tokenizer
t = Tokenizer()
t.fit_on_texts(docs)
vocab_size = len(t.word_index) + 1
# integer encode the documents
encoded_docs = t.texts_to_sequences(docs)
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 4
padded_docs = keras.preprocessing.sequence.pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)
print(padded_docs.shape[0])
arange_values = np.arrange(padded_docs.shape[0])
arange_values 

NameError: name 'Tokenizer' is not defined

In [51]:
import numpy as np

In [76]:
# load the whole embedding into memory
embeddings_index = dict()
f = open('C:\Dev\Work\DueDiligence_Material\DueDil\DueDiligenceUI\Models\glove.6B.100d.txt',encoding="utf8")
for line in f:
	values = line.split()
	word = values[0]
	coefs = np.asarray(values[1:], dtype='float32')
	embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

Loaded 400000 word vectors.


In [78]:
from numpy import zeros

# create a weight matrix for words in training docs
embedding_matrix = zeros((vocab_size, 100))
for word, i in t.word_index.items():
	embedding_vector = embeddings_index.get(word)
	if embedding_vector is not None:
		embedding_matrix[i] = embedding_vector

IndexError: index 15 is out of bounds for axis 0 with size 15

In [ ]:
embedding_matrix

In [5]:
from numpy import array
from numpy import asarray
from numpy import zeros
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Embedding
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])
# prepare tokenizer
t = Tokenizer()
t.fit_on_texts(docs)
vocab_size = len(t.word_index) + 1
print('vocab_size : ' + str(vocab_size))
# integer encode the documents
encoded_docs = t.texts_to_sequences(docs)
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = max([len(word.split()) for word in docs])
print('max_length : ' + str(max_length))
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)
# load the whole embedding into memory
embeddings_index = dict()
f = open('C:\\Users\\HIMS\\Downloads\\DueDilWorkspace\\DueDiligenceUI\\Models\\glove.6B.100d.txt', encoding='utf-8')
for line in f:
	values = line.split()
	word = values[0]
	coefs = asarray(values[1:], dtype='float32')
	embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))
# create a weight matrix for words in training docs
embedding_matrix = zeros((vocab_size, 100))
for word, i in t.word_index.items():
	embedding_vector = embeddings_index.get(word)
	if embedding_vector is not None:
		embedding_matrix[i] = embedding_vector
# define model
model = Sequential()
e = Embedding(vocab_size, 100, weights=[embedding_matrix], input_length=max_length, trainable=False)
model.add(e)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

vocab_size : 15
[[6, 2], [3, 1], [7, 4], [8, 1], [9], [10], [5, 4], [11, 3], [5, 1], [12, 13, 2, 14]]
max_length : 4
[[ 6  2  0  0]
 [ 3  1  0  0]
 [ 7  4  0  0]
 [ 8  1  0  0]
 [ 9  0  0  0]
 [10  0  0  0]
 [ 5  4  0  0]
 [11  3  0  0]
 [ 5  1  0  0]
 [12 13  2 14]]
Loaded 400000 word vectors.
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4, 100)            1500      
_________________________________________________________________
flatten_1 (Flatten)          (None, 400)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 401       
Total params: 1,901
Trainable params: 401
Non-trainable params: 1,500
_________________________________________________________________
None
Accuracy: 100.000000


In [ ]:
model.predict(x=['Hi Hemanshu is crimi'])

In [1]:

from keras.preprocessing.text import Tokenizer
# define 5 documents
docs = ['Rahul targets PM Rafale dares debate words September Deccan Herald DECHER English Copyright The Printers Mysore Private Ltd Mumbai Dhule Targetting prime minister Narendra Modi Rafale deal Congress president Rahul Gandhi Friday dared public debate corruptionI asking debate corruption let come debate Gandhi said addressing rally MMRDA grounds Bandra Kurla Complex Mumbai Referring Modi chowkidar speech several times said chowkidar chor hi nahidarpok bhi hai pointed Parliament prime minister refused answer pointed questions Congress Rafale deal During day Gandhi addressed two rallies Dhule KhandeshNorth Maharashtra Mumbai spoke Rafale issueDid Anil Ambani make Mirage Sukhois Gandhi said backdrop Pulwama terror attacks Indias strike terror camps Pakistan PakistanoccupiedKashmir He wanted know manufacturing contract given Anil Ambanis company Hindustan Aeronautics Ltd For years making planes Anil Ambani cannot even make paper planes Gandhi said Earlier paid tributes CRPF personnel died Pulwama terror attack IAF pilots airmen died Budgam helicopter crash Gandhi also said demonetisation failed exercise You stood queue outside banks Anil Ambani Nirav Modi Mehul Choksi Lalit Modi Vijay Mallya stood queuewhile stood queue outside banks made black money white said Modiji said electionsdo make prime minister make chowkidarand becomes PM puts Rs crore pockets Anil Ambani accused Document',
       'PMC bank fraud Mumbai Police puts airports alert prevent key accused fleeing words October India Today Online INTYON English Copyright Living Media Limited The Economic Offences Wing EOW issued preventive across country Punjab Maharashtra Cooperative Bank sent immigration security counters involved flee In past several frauds managed little success attained bringing back face law Nirav Modi Mehul Choksi Vijay Mallya fugitives borrowed huge loans duped banks using modus operandi On Monday per complaint RBI administrator registered case Banks Managing Director Joy Thomas Chairman Wareyam Singh HDIL Wadhawan Several others management also named Jasbir Mattha alleged period starting till August particular company paid turned NPA nonperforming asset But information disclosed banking norms Also officials prepared fake loan accounts records lesser amounts submitted led loss Rs crores said primary beneficiary losses suffered group companies connivance offered disbursement despite nonpayments various occasions amount misused debtors personal purposes leading major MD letter addressed chief manager confessedhidden fact regarding NPAs forging front board goes say dated September coverup protect reputation placed directions citing irregularities lending six months joined director later elected chairman account holders shocked learned restrictions allowed withdraw Many shattered disturbed protests state branches increased withdrawal limit sections IPC special investigation team formed investigate Read No need panic Indian system safe crisis MDs reveals dummy created hide Watch Was lack supervision behind Document']
# create the tokenizer
t = Tokenizer()
# fit the tokenizer on the documents
t.fit_on_texts(docs)
#print(t.word_counts)
#print(t.document_count)
#print(t.word_index)
print(len(t.word_index))
print(t.word_counts.shape)
#print(t.word_docs)

Using TensorFlow backend.


ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']

